version: '3.8'

services:
  db:
    image: postgres:14.9-alpine3.18
    env_file: 
      - ./.env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./infra/postgres_init/movies_database.ddl:/docker-entrypoint-initdb.d/movies_db.sql
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
  cinema_api:
    build: ./cinema_api/
    env_file:
      - ./.env
    depends_on:
      - db
      - elastic
      - redis
  auth_api:
    build: ./auth_api/
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    #ports:
      #- 127.0.0.1:8000:8000
  admin_panel:
    build: ./admin_panel/
    env_file:
      - ./.env
    volumes:
      - static_value:/opt/app/django_static/ 
      - media_value:/opt/app/django_media/ 
    depends_on:
      - db
    #ports:
      #- 127.0.0.1:8000:8000
  elastic:
    image: elasticsearch:8.6.2
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data:rw
  redis:
    image: redis:7.2.1-alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data:rw
  nginx: 
    image: nginx:1.19.3 
    ports: 
      - 80:80
    expose:
      - 80
    restart: always
    depends_on:
      - cinema_api
      - admin_panel
      - auth_api
    volumes: 
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/django_static/  
      - media_value:/var/html/django_media/
  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

volumes:
  postgres_data:
  redis_data:
  elastic_data:
  static_value:
  media_value:
